#[[docs]]
#  name = "Overview"
#  weight = 10
#  identifier = "overview"
#  url = "/docs/overview/"

#[[docs]]
#  name = "Tutorial"
#  weight = 20
#  identifier = "tutorial"
#  url = "/docs/tutorial/"

#[[docs]]
#  name = "How-to Guides"
#  weight = 30
#  identifier = "how-to"
#  url = "/docs/how-to/"

#[[docs]]
#  name = "Reference"
#  weight = 40
#  identifier = "reference"
#  url = "/docs/reference/"

#[[docs]]
#  name = "Contributing"
#  weight = 50
#  identifier = "contributing"
#  url = "/docs/contributing/"

#[[docs]]
#  name = "Help"
#  weight = 60
#  identifier = "help"
#  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

#[[main]]
#  name = "Showcase"
#  url = "/showcase/"
#  weight = 10

[[main]]
  name = "Tauhid"
  url = "/404.html"
  weight = 10

[[main]]
  name = "Fikih"
  url = "/404.html"
  weight = 10

[[main]]
  name = "Akhlak"
  url = "/404.html"
  weight = 10

[[main]]
  name = "Sejarah"
  url = "/404.html"
  weight = 10


#[[main]]
#  name = "GitHub repository"
#  weight = 10
#  url = "https://github.com/h-enk/doks"
#  post = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>'
#  parent = "community"
#  [main.params]
#   target = "_blank"

[[main]]
   name = "Buku"
   weight = 15
   url = "/404.html"

[[main]]
   name = "QnA"
   weight = 15
   url = "/404.html"

[[main]]
   name = "About"
   weight = 15
   url = "/404.html"

#[[main]]
#  name = "Discussions"
#  weight = 20
#  url = "https://github.com/h-enk/doks/discussions"
#  post = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>'
#  parent = "community"
#  [main.params]
#    target = "_blank"

#[[main]]
#  name = "Open Collective"
#  weight = 30
#  url = "https://opencollective.com/doks"
#  post = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>'
#  parent = "community"
#  [main.params]
#    target = "_blank"

# [[main]]
#   name = "Get Started"
#   weight = 30
#   identifier = "get-started"
#   url = "/docs/overview/introduction/"
#
# [[main]]
#   name = "Quick Start"
#   weight = 40
#   identifier = "quick-start"
#   url = "/docs/overview/quick-start/"
#   parent = "get-started"
#
# [[main]]
#   name = "Tutorial"
#   weight = 50
#   identifier = "tutorial"
#   url = "https://getdoks.org/docs/tutorial/introduction/"
#   parent = "get-started"

[[social]]
  name = "Youtube"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-youtube\"><path d=\"M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z\"></path><polygon points=\"9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02\"></polygon></svg>"
  url = "https://youtube.com/pustakaaswaja"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Facebook"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-facebook\"><path d=\"M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z\"></path></svg>"
  url = "https://facebook.com/pustakaaswaja"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Instagram"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-instagram\"><rect x=\"2\" y=\"2\" width=\"20\" height=\"20\" rx=\"5\" ry=\"5\"></rect><path d=\"M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z\"></path><line x1=\"17.5\" y1=\"6.5\" x2=\"17.51\" y2=\"6.5\"></line></svg>"
  url = "https://instagram.com/pustakaaswaja"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/pustakaaswaja"
  weight = 20

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 20

# [[footer]]
#   name = "Code of Conduct"
#   url = "/docs/contributing/code-of-conduct/"
#   weight = 30

# [[footer]]
#   name = "Open Collective"
#   url = "https://opencollective.com/doks"
#   weight = 40

[[secondary]]
  name = "Get Support"
  url = "/docs/help/faq/#can-i-get-support"
  weight = 10

[[showcase]]
  name = "Browse"
  weight = 10
  identifier = "browse"
  url = "/showcase/"

#[[tertiary]]
#  name = "Submit to Showcase"
#  url = "https://github.com/h-enk/doks/discussions?discussions_q=category%3A%22Show+and+tell%22"
#  weight = 10
