# Meta Data for SEO

## Homepage
title = "Pustaka Aswaja"
titleSeparator = "-"
titleAddition = "Materi Keislaman Lengkap"
description = "Pustaka Aswaja, pustaka digital, materi keislaman, ajaran Ahlus Sunnah Wal Jama'ah, koleksi sumber ilmiah, tulisan ulama terdahulu, panduan praktis ajaran islam, meningkatkan pemahaman Islam Sunni, sumber terpercaya."

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "pustakaaswaja.web.id"
titleHome = "Pustaka Aswaja"

## Twitter Cards
twitterSite = "@pustakaaswaja"
twitterCreator = "@moen_id"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Pustaka Aswaja"
schemaAuthor = "Misbahul Munir"
schemaAuthorTwitter = "https://twitter.com/moen_id"
schemaAuthorLinkedIn = "https://www.linkedin.com/moen_id"
schemaAuthorGitHub = "https://github.com/moen-id"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/pustakaaswaja"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/moen-id/pustakaaswaja"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "600"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"
# Footer
footer = "© 2023 The Pustaka Aswaja  <a class=\"text-muted\" href=\"https://moen.eu.org/\">Authors</a> | Documentation Digitized under CC BY 4.0. Copyright © 2023 The Pustaka Aswaja Digital. All rights reserved."


# Feed
copyRight = "Copyright © 2023 The Pustaka Aswaja Digital"

# Alert
alert = false
alertDismissable = true
# alertText = "Help Doks grow by supporting us on Open Collective. <a class=\"alert-link stretched-link\" href=\"https://opencollective.com/doks\" target=\"_blank\" rel=\"noopener\">Become a backer!</a>"
# alertText = "Better UX navigation, multilingual and i18n support, and more. <a class=\"alert-link stretched-link\" href=\"/blog/doks-v0.3/\">Check out what's new!</a>"
alertText = "The Jamstack at Scale: Building Sites for Audiences of Millions. <a class=\"alert-link stretched-link\" href=\"https://www.netlify.com/resources/ebooks/jamstack-at-scale?utm_campaign=Website%20-%20Whitepaper%20-%20Jamstack%20at%20Scale&utm_source=Homepage%20Announcement%20Bar\">Get the eBook!</a>"
# alertText = "Multi level section menu — <strong>automatically</strong> generated, and more. <a class=\"alert-link stretched-link\" href=\"/blog/doks-v0.4/\">Check out what's new!</a>"
# alertText = "What Doks future features are important to you? <a class=\"alert-link stretched-link\" href=\"https://docs.google.com/forms/d/e/1FAIpQLSe0DItAFv2cNSC0S_L6DQBw9ofB0ogYvZqeoWHHRX-Aal-5zQ/viewform?usp=sf_link\" target=\"_blank\" rel=\"noopener\">Take the 2021 Doks Survey</a>"

# Edit Page
docsRepo = "https://github.com/moen-id/pustakaaswaja"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  highLight = true
  multilingualMode = false # Not yet functional
  docsVersioning = false # Not yet functional

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
